# Generated by Django 4.2.4 on 2023-10-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comcase',
            fields=[
                ('comcase_id', models.AutoField(primary_key=True, serialize=False)),
                ('comcase_title', models.CharField(max_length=100)),
                ('comcase_image', models.CharField(max_length=100)),
                ('comcase_manufacturer', models.CharField(max_length=20)),
                ('comcase_size', models.CharField(max_length=20)),
                ('comcase_formfactors', models.CharField(max_length=20)),
                ('comcase_price', models.IntegerField()),
            ],
            options={
                'db_table': 'comcase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('cooler_id', models.AutoField(primary_key=True, serialize=False)),
                ('cooler_title', models.CharField(max_length=100)),
                ('cooler_image', models.CharField(max_length=100)),
                ('cooler_manufacturer', models.CharField(max_length=20)),
                ('cooler_cooling', models.CharField(max_length=20)),
                ('cooler_wattage', models.IntegerField()),
                ('cooler_price', models.IntegerField()),
            ],
            options={
                'db_table': 'cooler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('cpu_id', models.AutoField(primary_key=True, serialize=False)),
                ('cpu_title', models.CharField(max_length=100)),
                ('cpu_image', models.CharField(max_length=100)),
                ('cpu_manufacturer', models.CharField(max_length=20)),
                ('cpu_core', models.IntegerField()),
                ('cpu_thread', models.IntegerField()),
                ('cpu_clock', models.FloatField()),
                ('cpu_socket', models.CharField(max_length=20)),
                ('cpu_wattage', models.IntegerField()),
                ('cpu_price', models.IntegerField()),
            ],
            options={
                'db_table': 'cpu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mainboard',
            fields=[
                ('mainboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('mainboard_title', models.CharField(max_length=100)),
                ('mainboard_image', models.CharField(max_length=100)),
                ('mainboard_manufacturer', models.CharField(max_length=20)),
                ('mainboard_cpu', models.CharField(max_length=20)),
                ('mainboard_socket', models.CharField(max_length=20)),
                ('mainboard_chipset', models.CharField(max_length=20)),
                ('mainboard_formfactors', models.CharField(max_length=20)),
                ('mainboard_wattage', models.IntegerField()),
                ('mainboard_price', models.IntegerField()),
            ],
            options={
                'db_table': 'mainboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('memory_id', models.AutoField(primary_key=True, serialize=False)),
                ('memory_title', models.CharField(max_length=100)),
                ('memory_image', models.CharField(max_length=100)),
                ('memory_manufacturer', models.CharField(max_length=20)),
                ('memory_capacity', models.IntegerField()),
                ('memory_clock', models.IntegerField()),
                ('memory_wattage', models.IntegerField()),
                ('memory_price', models.IntegerField()),
            ],
            options={
                'db_table': 'memory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('power_id', models.AutoField(primary_key=True, serialize=False)),
                ('power_title', models.CharField(max_length=100)),
                ('power_image', models.CharField(max_length=100)),
                ('power_manufacturer', models.CharField(max_length=20)),
                ('power_formfactors', models.CharField(max_length=20)),
                ('power_output', models.IntegerField()),
                ('power_price', models.IntegerField()),
            ],
            options={
                'db_table': 'power',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteOrder',
            fields=[
                ('quote_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('product_count', models.IntegerField()),
                ('product_price', models.IntegerField()),
            ],
            options={
                'db_table': 'quote_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_title', models.CharField(max_length=100)),
                ('storage_image', models.CharField(max_length=100)),
                ('storage_manufacturer', models.CharField(max_length=20)),
                ('storage_device', models.CharField(max_length=20)),
                ('storage_capacity', models.CharField(max_length=20)),
                ('storage_wattage', models.IntegerField()),
                ('storage_price', models.IntegerField()),
            ],
            options={
                'db_table': 'storage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_num', models.AutoField(db_column='USER_NUM', primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_column='USER_ID', max_length=30)),
                ('user_name', models.CharField(db_column='USER_NAME', max_length=30)),
                ('user_password', models.CharField(db_column='USER_PASSWORD', max_length=30)),
                ('user_birth', models.CharField(db_column='USER_BIRTH', max_length=10)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Videocard',
            fields=[
                ('videocard_id', models.AutoField(primary_key=True, serialize=False)),
                ('videocard_title', models.CharField(max_length=100)),
                ('videocard_image', models.CharField(max_length=100)),
                ('videocard_manufacturer', models.CharField(max_length=20)),
                ('videocard_chipset', models.CharField(max_length=20)),
                ('videocard_capacity', models.IntegerField()),
                ('videocard_clock', models.IntegerField()),
                ('videocard_wattage', models.IntegerField()),
                ('videocard_price', models.IntegerField()),
            ],
            options={
                'db_table': 'videocard',
                'managed': False,
            },
        ),
    ]
